### ISSUE TITLE
Generate osbuild stages documentation

### ISSUE THREAD

**Issue by ochosi** [osbuild/osbuild.github.io#71]
Now that the json schemas exist outside the Python code, we should be able to just generate the documentation for each stage and publish it on the website.

The target should be: https://github.com/osbuild/osbuild.github.io/tree/main/docs/developer-guide/02-projects/osbuild

And a script similar to: https://github.com/osbuild/osbuild.github.io/blob/main/scripts/pull_readmes.py

**Comment by supakeen** [comment]
See: #77
